name: Build and Release Container

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t noble-curl

      - name: Create Docker container
        run: docker create --name noble.curl noble-curl /bin/true

      - name: Export and compress Docker container
        run: docker export noble.curl | gzip > noble-curl.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: noble-curl.tar.gz
